# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build Flutter APK with flavor and mode"
  lane :flutter_build do |options|

    flavor = options[:flavor] || "dev"
    mode   = options[:mode]   || "debug"

    target = "lib/main_#{flavor}.dart"

    UI.message("🚀 Building flavor=#{flavor}, mode=#{mode}")

    sh("flutter --version")
    sh("flutter pub get")

    sh(
      "flutter build apk " \
      "--#{mode} " \
      "--flavor #{flavor} " \
      "-t #{target}"
    )
  end
end

