name: Flutter CI (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: "Enter branch name"
        required: true
        default: main
        type: string

      app-name:
        description: "Enter app name"
        required: true
        default: tanpura
        type: choice
        options:
          - tanpura

      flavor:
        description: "Select build flavor"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod

      build-mode:
        description: "Select build mode"
        required: true
        default: debug
        type: choice
        options:
          - debug
          - release

      flutter-version:
        description: "Select flutter version"
        required: true
        default: "3.32.0"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 0 Set build variables
      - name: Set build variables
        run: |
          echo "FLAVOR=${{ github.event.inputs.flavor }}" >> $GITHUB_ENV
          echo "MODE=${{ github.event.inputs.build-mode }}" >> $GITHUB_ENV
          echo "TARGET=lib/main_${{ github.event.inputs.flavor }}.dart" >> $GITHUB_ENV

      # 1️ Checkout selected branch
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch-name }}
          submodules: "recursive"

      # 2️ Java setup
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️ Flutter setup
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ github.event.inputs.flutter-version }}
          cache: true

      # 4 Dependencies
      - name: Flutter pub get
        working-directory: apps/${{ github.event.inputs.app-name }}
        run: flutter pub get

      # 5 Build APK
      - name: Build APK via Fastlane
        working-directory: apps/${{ github.event.inputs.app-name }}/android
        run: |
          fastlane flutter_build \
            flavor:${FLAVOR} \
            mode:${MODE}

      # 6 Upload APK
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.event.inputs.flavor }}-${{ github.event.inputs.build-mode }}-apk
          path: apps/${{ github.event.inputs.app-name }}/build/app/outputs/flutter-apk/*.apk
